import {blend,linearToSrgb,srgbToLinear,clamp} from './color.js';
export const LESSONS=[
  {id:'intro',part:'Part 0 · はじめに',title:'この教材とラボの使い方',core:'撮影処理は、素材を重ねる「合成」と、色・光・ぼけを整える「効果」の組み合わせです。アニメのセルと背景、実写の人物とロケ背景は、素材が違っても見比べる項目は共通です。',how:'最初はサンプルのキャラと夕焼けを使います。「背景に合わせる」を押し、レイヤーの目のボタンで各段を消してみましょう。A/B の左が効果なし、右が現在です。気になる変化は教科書で確認し、元の設定には Undo で戻れます。',failure:'最初から効果を全部強くすると、何が効いたのか分からなくなります。まず環境色、次に明暗、最後に縁という順に一つずつ観察します。',code:'素材 → 合成 → 効果 → 出力',question:'何から試すと、効果の役割が分かりやすい？',options:['一つずつ ON / OFF にして比べる','すべての強さを最大にする'],answer:0,explain:'一つだけ変えると、どの処理が色・明暗・縁を変えたか追えます。',caption:'素材、色合わせ、光、出力を分けて考えます。'},
  {id:'pipeline',part:'Part 1 · 基礎',title:'撮影とは：背景・セル・BOOK・効果',core:'アニメでは背景、その上にセル（キャラ）、さらに手前に前景（BOOK）を置きます。同じ画像でも上下関係が変われば、どれが前に見えるかが変わります。調整レイヤーは下にある合成結果を変え、レイヤーの効果はその一枚を変えます。',how:'「読み込み」から前景画像を足すか、単色レイヤーを追加します。不透明度を下げてから、レイヤーを上下へ移動してください。全体の効果にぼかしを足した場合と、キャラだけに足した場合を比べます。',failure:'全体の効果に色調整を置くと、既に良い色の背景まで変わります。キャラだけを直すならキャラの効果、またはキャラにクリップした調整を選びます。',code:'背景 → キャラ → 前景（BOOK）→ 全体の効果',question:'キャラだけの露出を変えたいときは？',options:['全体の効果に露出を足す','キャラの効果に色調整を足す'],answer:1,explain:'キャラの効果なら、背景と前景の画素はそのままです。',caption:'左から奥→手前。レイヤー一覧では手前が上に表示されます。'},
  {id:'alpha',part:'Part 1 · 基礎',title:'アルファと premultiplied',core:'アルファは、その画素がどれだけ素材に覆われているかを表します。合成途中では RGB にアルファを掛けた値を使うと、半透明の色を正しく足せます。書き出す PNG ではこれを解き、色と透明度を別々に保存します。',how:'白い単色レイヤーを黒の上に置き、不透明度を0.5にします。キャラPNGの縁も拡大してください。透明部分の黒が色に混ざる処理では、輪郭に暗いフチが出ます。ラボは読み込みから出力まで半透明を管理します。',failure:'既にアルファを掛けた画像にもう一度掛けると、縁が暗くなります。Canvas 2D の8bit変換でも丸めが起きるため、このラボのPNG書き出しは画素を直接保存します。',code:'premultiplied RGB = RGB * alpha',question:'半透明の赤を透明PNGに書き出すとき、色は？',options:['赤を保ち、透明度だけを別に保存する','赤を暗くして、透明度も下げる'],answer:0,explain:'RGBを暗くする必要はありません。色を割り戻してから、アルファを独立して保存します。',caption:'アルファを二重に掛けると縁が暗くなります。'},
  {id:'linear',part:'Part 1 · 基礎',title:'リニアとガンマ：合成の明るさ',core:'sRGBは表示に適した値へ光を曲げたものです。光の量に比例するリニアへ戻して足すと、白と黒の50%合成はsRGBで約188になります。sRGBの数値のまま計算するガンマ空間では約128です。',how:'白50%と黒のプリセットを開き、設定の「合成空間」を切り替えます。同じ不透明度でも明るさが変わります。次にぼかしやグローでも比較し、どちらの見た目が必要かを考えます。',failure:'アプリ名だけで結果を決めつけないでください。After EffectsやNukeも色管理と作業空間の設定に依存します。リニアは光として自然、ガンマは慣れた画作りに使われます。',code:'linear: sRGB → 光の値 → 合成 → sRGB',question:'リニアで白50%を黒に重ねると？',options:['約128','約188'],answer:1,explain:'線形の0.5は、表示用のsRGBでは約0.735（188/255）です。',caption:'同じ半透明の白。左はガンマの128、右はリニアの188。'},
  {id:'blend',part:'Part 1 · 基礎',title:'ブレンドモード辞典',core:'ブレンドは下の色と上の色の組み合わせ方です。乗算は影、スクリーンは光、カラーは明るさを保った色寄せに使えます。加算はHDRの作業値なら1を超えられますが、表示やPNGでは最終的に範囲を収めます。',how:'単色レイヤーを選び、ブレンドの16種類を切り替えます。下の図でもモードを比較できます。カラーと乗算で、色だけが変わる場合と暗さまで変わる場合を見分けましょう。',failure:'ガンマの計算で見慣れたスクリーンは、リニアでは違う明るさになります。モード名と不透明度だけで別アプリの結果を再現しようとせず、合成空間も揃えます。',code:'multiply(b, s) = b * s; screen(b, s) = b + s - b * s',question:'背景の色相を寄せつつ明るさを保ちやすいのは？',options:['カラー','乗算'],answer:0,explain:'カラーはW3Cの輝度を保って上の色を移します。乗算は暗さも変えます。',caption:'下のグレーに上の暖色を重ねた結果。モードで比べてください。'},
  {id:'scopes',part:'Part 1 · 基礎',title:'スコープの読み方',core:'ヒストグラムは明るさの分布、波形は画面の横位置ごとの明るさ、ベクトルスコープは色の偏りを見ます。目の順応や周囲の色に惑わされず、キャラと背景の差を数値として比べる道具です。',how:'対象を「背景」「キャラ」と切り替え、山の位置を比べます。「前を記録」してオートマッチを掛け、黄の前と緑の後を重ねましょう。波形ではキャラの位置だけ明るく飛び出していないかを見ます。',failure:'ヒストグラムの山を完全に一致させる必要はありません。顔を読みやすくするため、キャラのコントラストや彩度を少し残します。スコープは目的に合うかを判断する補助です。',code:'分布を見る / 位置を見る / 色の方向を見る',question:'どの横位置が明るすぎるか分かるのは？',options:['ヒストグラムだけ','波形'],answer:1,explain:'波形の横軸は画面の横位置です。ヒストグラムには位置の情報がありません。',caption:'分布の一致と、絵として読みやすいことは別に判断します。'},
  {id:'why-float',part:'Part 2 · なじませる',title:'なぜキャラが浮くか：7つの不一致',core:'浮いて見える原因は、色かぶり・明暗の範囲・彩度・コントラスト・エッジの硬さ・粒子・光の方向の不一致です。暖色を一枚重ねても、夜景に対して白すぎる服や鋭すぎる輪郭は残ります。',how:'背景合わせを開き、環境色、統計マッチ、明暗の範囲を一段ずつ消します。さらにキャラを選び、ライトラップ、空気感、エッジ、グレインを切り替えます。どの不一致が一番強いかを言葉にしてください。',failure:'「浮くからグローを足す」と原因を決めずに処理すると、光っているのに馴染まない絵になります。明暗、色、輪郭のどれが違うのかを先に調べます。',code:'色 / 明暗 / 彩度 / コントラスト / 縁 / 粒子 / 光の方向',question:'夜景に白いキャラが浮いている。最初に調べるのは？',options:['明暗の範囲と露出','フレアの数'],answer:0,explain:'夜の背景に対してキャラの明部が高すぎる可能性があります。波形で確認します。',caption:'一つずつ原因を分けて直すと、効果を重ねすぎずに済みます。'},
  {id:'ambient',part:'Part 2 · なじませる',title:'環境色をかぶせる',core:'背景の平均色で単色レイヤーを作り、キャラへクリップしてカラー25%で重ねます。これが最も簡単な色寄せです。平均色を画面全体から取るか、キャラの背後から取るかで結果が変わります。',how:'環境色のレイヤーを選び、不透明度を0から0.4へ動かします。ブレンドをカラーから乗算に替えると、暗くなる理由も観察できます。青空と緑の地面がある背景では、測る範囲を替えてレポートの色を比べましょう。',failure:'環境色だけでは明暗の幅が変わりません。夜の室内では色が青くなっても服の明るさが残ります。明暗の範囲か露出を次に直します。',code:'背景の平均色 → 単色 → キャラにクリップ → カラー25%',question:'空が青くても地面に立つキャラには？',options:['必ず空全体の色だけを使う','キャラの背後や地面の反射色も考える'],answer:1,explain:'局所的な環境光が大切です。ラボはキャラの領域を1.5倍に広げた背後を既定で測ります。',caption:'クリッピングすると環境色がキャラの形だけに掛かります。'},
  {id:'stats',part:'Part 2 · なじませる',title:'統計で合わせる',core:'Oklabで平均と散らばりを測り、背景に近づけます。Lは明るさ、a・bは色の方向です。強さ0なら元の色、1なら目標の平均へ寄ります。散らばりの倍率は0.5〜2に制限して破綻を抑えます。',how:'統計マッチを選び、強さを0、0.6、1と変えます。ベクトルスコープの中心とレポートの平均距離を見ます。1にすると肌や髪の固有色まで背景へ寄ることも観察します。',failure:'統計の一致は美しさの保証ではありません。背景がほぼ単色のときは必要な色まで消えます。色域外の値は表示時に収められるため、倍率制限と出力変換によって標準偏差が完全一致しない場合もあります。',code:'result = mix(original, (original - sourceMean) * ratio + targetMean, strength)',question:'強さ1がいつも最適？',options:['固有色や読みやすさを見て弱めることもある','統計が合うなら必ず最適'],answer:0,explain:'統計は指標です。肌・髪の識別やキャラの主役らしさも残します。',caption:'平均を寄せ、散らばりを調整します。強さ0では元の色を保ちます。'},
  {id:'range',part:'Part 2 · なじませる',title:'明暗の範囲を合わせる',core:'暗い側1%の境界（p1）と明るい側99%の境界（p99）を使い、明暗の幅を合わせます。たった一つの白い画素や黒い画素に引っ張られにくい測り方です。トゥーンの平坦な塗りと暗い背景の差を補います。',how:'夜の背景と明暗の範囲のプリセットを開きます。波形をキャラに切り替え、調整前後の明るい端が下がる様子を確認します。強さを下げ、顔が読める明るさを探してください。',failure:'暗部まで背景の黒へ合わせすぎると、線や髪が潰れます。p1・p99の範囲を移した後、顔と服の境界が残るか拡大して見ます。',code:'キャラの p1 … p99 → 背景の p1 … p99',question:'最大値・最小値だけでなく p1・p99 を使う理由は？',options:['必ず明るくなるから','少数の極端な画素に引っ張られにくいから'],answer:1,explain:'外れ値を除き、画像の主要な明暗の範囲を扱えます。',caption:'幅と中心の両方を見ると、露出だけでは直らない差が分かります。'},
  {id:'wrap-fog',part:'Part 2 · なじませる',title:'ライトラップと空気感',core:'ライトラップは背景をぼかし、キャラの縁の内側へ足します。空気感はキャラ全体を空気の色へ少し混ぜます。前者は逆光の回り込み、後者は距離によるコントラストの低下を表します。',how:'キャラのライトラップを0から0.7へ変え、輪郭と中心を見比べます。空気感の距離を0から0.3へ動かすと、中心も背景寄りになります。背景を夜に替えたときは、ラップを弱める判断も試してください。',failure:'順光なのに縁を強く光らせると、切り抜きの輪郭をかえって強調します。空気感を上げすぎると手前のキャラまで遠くへ引っ込みます。',code:'wrap = 背景のぼかし * 縁の内側; fog = mix(キャラ, 空気の色, 距離)',question:'キャラ全体のコントラストを遠景に近づけるのは？',options:['空気感','ライトラップだけ'],answer:0,explain:'空気感は全体を環境色へ混ぜます。ライトラップは主に縁です。',caption:'縁だけを変える処理と、全体を変える処理を区別します。'},
  {id:'edge-grain',part:'Part 2 · なじませる',title:'エッジと粒子を合わせる',core:'キャラの輪郭だけが鋭く、背景だけがぼけていると、同じ画面に存在する感じが弱まります。背景のエッジ勾配と高周波成分を測り、縁の柔らかさと粒子の量を近づけます。粒子は静止画なので固定の種で再現します。',how:'キャラを拡大し、エッジぼかしを短辺比0から0.004程度で比較します。グレインの強さ、粒の大きさ、種を変え、同じ種へ戻すと同じ粒になることを確かめます。',failure:'グレインで線や目の情報を壊さないようにします。背景の細かい木の葉も高周波として測られるため、自動値は出発点です。効果を切り替え、粒子として必要な量か確認します。',code:'半径は短辺比 / グレインは固定 seed',question:'静止画で同じ種と設定に戻すと？',options:['毎回ランダムに変わる','同じ粒子を再現する'],answer:1,explain:'固定した種と画素位置から粒子を作るので、再読み込みでも再現できます。',caption:'縁は小さな半径から。ノイズは細部を消さない量にします。'},
  {id:'direction',part:'Part 2 · なじませる',title:'光の方向をそろえる：パラ',core:'パラはグラデーションにブレンドと不透明度を組み合わせたものです。黒パラは乗算で暗くし、白パラはスクリーンや加算で明るくします。背景の左右の明るさから、キャラのどちら側を暗くするか考えます。',how:'黒パラの角度を回し、開始・終了位置を動かします。キャラにクリップしてから光源の反対側を少し暗くしてください。背景合わせは左右のL平均差が0.08以上のときだけ方向の段を作ります。',failure:'明るい側に白パラを強く足すと、トゥーンの塗りが白く飛びます。まず影側を控えめに落とし、必要な場合だけ白パラを足します。',code:'黒パラ = グラデーション + 乗算 + 不透明度',question:'左から光が来るとき、まず試す黒パラは？',options:['右側を少し暗くする','左側だけを真っ黒にする'],answer:0,explain:'光源の反対側を軽く落として方向をそろえます。',caption:'光の向きとパラの角度を揃えます。'},
  {id:'automatch',part:'Part 2 · なじませる',title:'オートマッチの中身とレポート',core:'ボタンは結果を焼き込まず、環境色・統計マッチ・明暗の範囲・条件付きのパラをグループに作ります。縁の処理はキャラの効果です。レポートは元と背景、処理後の平均、明暗の範囲、平均距離を実際の画素から測ります。',how:'段の選択で環境色だけを有効にして実行し、次に統計と明暗を加えます。背景合わせグループが増殖せず更新されること、Undo一回で前へ戻ることも確かめます。レポートの距離が減っていても、顔や服の色が読み取れるか目で確認します。',failure:'背景やキャラの位置を変えた後は、以前の統計がそのまま最適とは限りません。再実行して測り直します。設定を手で変えた後のレポートを「現在の測定結果」と取り違えないでください。',code:'測定 → 編集できる段を作る → 再測定 → 目で判断',question:'レポートの距離が小さくなったら、それだけで完成？',options:['はい。数値だけで決められる','いいえ。固有色・輪郭・読みやすさも確認する'],answer:1,explain:'色の平均距離は一つの尺度です。意図した絵になったかを最後に見ます。',caption:'自動値から始めて、自分の目で仕上げるための道具です。'}
];
const $=id=>document.getElementById(id),el=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;};
function figure(canvas,id,mode='color'){
  const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.fillStyle='#142935';ctx.fillRect(0,0,w,h);
  ctx.font='15px sans-serif';ctx.textAlign='center';
  if(id==='linear'||id==='alpha'){
    for(let i=0;i<2;i++){ctx.fillStyle=i?'rgb(188,188,188)':'rgb(128,128,128)';ctx.fillRect(30+i*w/2,20,w/2-60,90);ctx.fillStyle='#d5e0e7';ctx.fillText(i?'リニア · 188':'ガンマ · 128',w*(i+.5)/2,139);}
  }else if(id==='blend'||id==='ambient'){
    for(let x=0;x<w-40;x++){
      const base=[x/(w-40),x/(w-40),x/(w-40)],s=[.65,.24,.09];
      const c=blend(mode,base,s).map(v=>Math.round(clamp(linearToSrgb(v))*255));
      ctx.fillStyle='rgb('+c.join(',')+')';ctx.fillRect(20+x,20,1,95);
    }ctx.fillStyle='#d5e0e7';ctx.fillText('下のグレー：暗い → 明るい / 上：暖色',w/2,144);
  }else if(id==='direction'){
    const g=ctx.createLinearGradient(25,0,w-25,0);g.addColorStop(0,'#f6ca8b');g.addColorStop(1,'#283750');ctx.fillStyle=g;ctx.fillRect(25,20,w-50,95);ctx.fillStyle='#d5e0e7';ctx.fillText('光源側 ←                      → 影側へ黒パラ',w/2,144);
  }else if(['stats','range','scopes'].includes(id)){
    const draw=(center,spread,color)=>{ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();for(let x=20;x<w-20;x++){const y=125-95*Math.exp(-(((x/w-center)/spread)**2));if(x===20)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.stroke();};
    draw(.68,.13,'#ffd166');draw(.4,.18,'#6ee7b7');ctx.fillStyle='#d5e0e7';ctx.fillText('黄：キャラの分布 / 緑：背景の分布（模式図）',w/2,151);
  }else{
    const labels=['素材','色・明暗','光・ぼけ','出力'];
    labels.forEach((label,i)=>{const x=15+i*w/4;ctx.fillStyle=['#365970','#2c6670','#60717b','#387960'][i];ctx.fillRect(x,35,w/4-25,65);ctx.fillStyle='#eff6fb';ctx.fillText(label,x+(w/4-25)/2,74);if(i<3)ctx.fillText('→',x+w/4-7,73);});
    ctx.fillStyle='#a3b6c2';ctx.fillText('一段ずつ変えて、目とスコープで確かめる',w/2,140);
  }
}
export function initLessons({tryPreset,openBook,notify}){
  const sections=[],buttons=[];
  for(const [index,l] of LESSONS.entries()){
    const section=el('section');section.className='lesson';section.dataset.lessonId='compolab-'+l.id;section.id='compolab-'+l.id;
    const part=el('p',l.part);part.className='part';section.append(part,el('h2',l.title),el('h3','核'),el('p',l.core),el('code',l.code));
    const fig=el('figure'),canvas=el('canvas');canvas.width=640;canvas.height=170;canvas.setAttribute('role','img');canvas.setAttribute('aria-label',l.caption);fig.append(canvas,el('figcaption',l.caption));section.append(fig);figure(canvas,l.id);
    if(l.id==='blend'){const select=el('select');select.setAttribute('aria-label','図のブレンド');for(const [key,name] of Object.entries({normal:'通常',multiply:'乗算',screen:'スクリーン',overlay:'オーバーレイ',darken:'比較（暗）',lighten:'比較（明）',colordodge:'覆い焼き',colorburn:'焼き込み',hardlight:'ハードライト',softlight:'ソフトライト',difference:'差',add:'加算',hue:'色相',saturation:'彩度',color:'カラー',luminosity:'輝度'})){const option=el('option',name);option.value=key;select.append(option);}select.value='color';select.onchange=()=>figure(canvas,l.id,select.value);fig.append(select);}
    section.append(el('h3','やってみる'),el('p',l.how));const run=el('button','ラボで試す');run.className='primary try-lab';run.onclick=()=>tryPreset(l.id);section.append(run,el('h3','よくある失敗'),el('p',l.failure));
    const quiz=el('div');quiz.className='quiz';quiz.dataset.answer=l.answer;quiz.append(el('b','理解チェック：'+l.question));const feedback=el('p');feedback.className='fb';feedback.setAttribute('aria-live','polite');
    l.options.forEach((text,i)=>{const button=el('button',text);button.className='opt';button.onclick=()=>{feedback.textContent=(i===l.answer?'その通りです。':'もう一度考えてみましょう。')+l.explain;};quiz.append(button);});quiz.append(feedback);section.append(quiz);
    const footer=el('div');footer.className='lesson-footer';const done=el('label','理解した'),checkbox=el('input');checkbox.type='checkbox';done.className='done';done.prepend(checkbox);footer.append(done);
    if(index<LESSONS.length-1){const next=el('button','次の章 →');next.onclick=()=>location.hash='compolab-'+LESSONS[index+1].id;footer.append(next);}
    section.append(footer);$('lessons').append(section);sections.push(section);
    const nav=el('button',String(index+1).padStart(2,'0')+'  '+l.title);nav.onclick=()=>location.hash='compolab-'+l.id;$('lesson-list').append(nav);buttons.push(nav);
  }
  const state=new window.LessonState('compolab',sections);
  const progress=()=>{$('lesson-progress').textContent=state.done.size+' / 14 理解した';sections.forEach((s,i)=>{const done=state.done.has(s.dataset.lessonId);s.querySelector('.done input').checked=done;buttons[i].classList.toggle('done',done);});};
  sections.forEach(s=>s.querySelector('.done input').onchange=e=>{if(e.target.checked)state.done.add(s.dataset.lessonId);else state.done.delete(s.dataset.lessonId);if(!state.save())notify('進捗を保存できません。このまま学習は続けられます。',true);progress();});
  const select=()=>{const hash=location.hash.replace(/^#/,'');const valid=sections.some(s=>s.dataset.lessonId===hash)||LESSONS.some(l=>l.id===hash);
    const normalized=LESSONS.some(l=>l.id===hash)?'#compolab-'+hash:location.hash;const index=state.index(normalized);
    sections.forEach((s,i)=>s.classList.toggle('active',i===index));buttons.forEach((b,i)=>b.classList.toggle('active',i===index));if(valid)openBook();
  };window.addEventListener('hashchange',select);progress();select();
}
