const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8772/tools/morse/');
 await page.locator('#tree .node').first().waitFor();
 assert.equal(await page.locator('#repeat').inputValue(),'repeat');
 assert.equal(await page.locator('#group').inputValue(),'all');
 assert.deepEqual(await page.locator('#group option').allTextContents(),['英数字すべて','A–Z','0–9']);
 await page.locator('#sound').click();
 assert.equal(await page.locator('#sound').getAttribute('aria-pressed'),'true');
 let left=await page.locator('#dit').boundingBox(), right=await page.locator('#dah').boundingBox();
 assert.equal(Math.round(right.x-left.x-left.width),18);
 // Real mouse hover, stationary for more than five marks, no synthetic event dispatch.
 await page.mouse.move(left.x+left.width/2,left.y+left.height/2);
 await page.waitForTimeout(280);
 assert.ok((await page.locator('#sequence').textContent()).length>=2);
 await page.waitForTimeout(900);
 assert.equal(await page.evaluate(()=>held.has('mouse')),true);
 const firstTone=await page.evaluate(()=>toneUntil);
 await page.waitForTimeout(300);
 assert.ok(await page.evaluate(t=>toneUntil>t,firstTone),'Stationary pointer continues sounding after 5 marks');
 await page.mouse.move(left.x+left.width+9,left.y+80);
 await page.waitForTimeout(850);
 assert.equal(await page.evaluate(()=>held.size),0);
 assert.equal(await page.evaluate(()=>sequence),'');
 await page.locator('#clear').click();
 // A short trip across both paddles should produce A with no extra marks.
 await page.getByText('打鍵の設定 · 速度・連打・音量',{exact:true}).click();
 await page.locator('#auto').uncheck();
 await page.locator('#dit').scrollIntoViewIfNeeded();
 left=await page.locator('#dit').boundingBox();right=await page.locator('#dah').boundingBox();
 await page.mouse.move(left.x+left.width/2,left.y+80);
 await page.waitForTimeout(30);
 await page.mouse.move(left.x+left.width+9,left.y+80);
 await page.waitForTimeout(130);
 await page.mouse.move(right.x+right.width/2,right.y+80);
 await page.waitForTimeout(30);
 await page.mouse.move(left.x+left.width+9,left.y+80);
 await page.waitForTimeout(310);
 await page.locator('#confirm').click();
 assert.equal(await page.locator('#transcript').textContent(),'A');
 await page.getByRole('button',{name:'文字練習',exact:true}).click();
 assert.equal(await page.locator('[data-family]').count(),0);
 const first=await page.locator('#target').textContent();
 const code=await page.evaluate(char=>MORSE[char],first);
 for(const symbol of code){await page.keyboard.press(symbol==='.'?'f':'j');await page.waitForTimeout(symbol==='.'?160:300);}
 await page.keyboard.press('Enter');
 await page.waitForTimeout(450);
 assert.notEqual(await page.locator('#target').textContent(),first,'Correct answer automatically advances to a different question');
 assert.equal(await page.locator('#target .done').count(),0);
 // Switching modes cancels the pending automatic question.
 await page.evaluate(()=>{accept(target);});
 await page.getByRole('button',{name:'自由入力',exact:true}).click();
 await page.waitForTimeout(450);
 assert.equal(await page.evaluate(()=>mode),'free');
 assert.equal(await page.evaluate(()=>target),'');
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'morse-edge-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No page overflow');
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'morse-edge-mobile.png'),fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('PASS Edge: stationary hover beyond 5 marks, audible context, release, compact geometry, mouse A, automatic next question and mode cancellation, keyboard, mobile width, no JS errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});