const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8772/tools/morse/');
 await page.locator('#tree .node').first().waitFor();
 assert.equal(await page.evaluate(()=>window.confirm.toString().includes('[native code]')),true);
 assert.equal(await page.evaluate(()=>typeof window.commitChar),'undefined');
 await page.evaluate(()=>{
   window.testPulseCount=0;
   for(const paddle of document.querySelectorAll('.paddle')){
     let last=false;
     new MutationObserver(()=>{const active=paddle.classList.contains('firing');if(active&&!last)window.testPulseCount++;last=active;}).observe(paddle,{attributes:true,attributeFilter:['class']});
   }
   window.dispatchEvent(new KeyboardEvent('keydown',{key:'f'}));
   window.dispatchEvent(new KeyboardEvent('keyup',{key:'f'}));
 });
 await page.locator('#clear').click();
 assert.equal(await page.locator('#repeat').inputValue(),'repeat');
 assert.equal(await page.locator('#group').inputValue(),'all');
 assert.deepEqual(await page.locator('#group option').allTextContents(),['英数字すべて','A–Z','0–9']);
 await page.locator('#sound').click();
 assert.equal(await page.locator('#sound').getAttribute('aria-pressed'),'true');
 let left=await page.locator('#dit').boundingBox(), right=await page.locator('#dah').boundingBox();
 assert.equal(Math.round(right.x-left.x-left.width),18);
 // Real mouse hover, stationary for more than five marks, no synthetic event dispatch.
 await page.mouse.move(left.x+left.width/2,left.y+left.height/2);
 await page.waitForTimeout(280);
 assert.ok((await page.locator('#sequence').textContent()).length>=2);
 await page.waitForTimeout(900);
 const firstTone=await page.evaluate(()=>window.testPulseCount);
 await page.waitForTimeout(300);
 assert.ok(await page.evaluate(t=>window.testPulseCount>t,firstTone),'Stationary pointer continues sounding after 5 marks');
 await page.mouse.move(left.x+left.width+9,left.y+80);
 await page.waitForTimeout(850);
 assert.equal(await page.locator('#sequence').textContent(),'');
 assert.equal(await page.locator('.paddle.firing').count(),0);
 await page.locator('#clear').click();
 // A short trip across both paddles should produce A with no extra marks.
 await page.getByText('打鍵の設定 · 速度・連打・音量',{exact:true}).click();
 await page.locator('#auto').uncheck();
 await page.locator('#dit').scrollIntoViewIfNeeded();
 left=await page.locator('#dit').boundingBox();right=await page.locator('#dah').boundingBox();
 await page.mouse.move(left.x+left.width/2,left.y+80);
 await page.waitForTimeout(30);
 await page.mouse.move(left.x+left.width+9,left.y+80);
 await page.waitForTimeout(130);
 await page.mouse.move(right.x+right.width/2,right.y+80);
 await page.waitForTimeout(30);
 await page.mouse.move(left.x+left.width+9,left.y+80);
 await page.waitForTimeout(310);
 await page.locator('#confirm').click();
 assert.equal(await page.locator('#transcript').textContent(),'A');
 await page.getByRole('button',{name:'文字練習',exact:true}).click();
 assert.equal(await page.locator('[data-family]').count(),0);
 const first=await page.locator('#target').textContent();
 const code=(await page.locator('#hint-text').textContent()).trim().split(/\s+/).pop().replace(/·/g,'.').replace(/−/g,'-');
 for(const symbol of code){await page.keyboard.press(symbol==='.'?'f':'j');await page.waitForTimeout(symbol==='.'?160:300);}
 await page.keyboard.press('Enter');
 await page.waitForTimeout(450);
 assert.notEqual(await page.locator('#target').textContent(),first,'Correct answer automatically advances to a different question');
 assert.equal(await page.locator('#target .done').count(),0);
 // Switching modes cancels the pending automatic question.
 const nextCode=(await page.locator('#hint-text').textContent()).trim().split(/\s+/).pop();
 for(const symbol of nextCode){await page.keyboard.press(symbol==='·'?'f':'j');await page.waitForTimeout(symbol==='·'?160:300);}
 await page.keyboard.press('Enter');
 await page.getByRole('button',{name:'自由入力',exact:true}).click();
 await page.waitForTimeout(450);
 assert.equal(await page.locator('[data-mode=free]').getAttribute('aria-pressed'),'true');
 assert.equal(await page.locator('#target').textContent(),'');
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'morse-edge-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No page overflow');
 await page.screenshot({path:path.join(require('node:os').tmpdir(),'morse-edge-mobile.png'),fullPage:true});
 // Preferences survive reload, while text and audio activation do not.
 await page.locator('#speed').fill('23');await page.locator('#speed').dispatchEvent('input');
 await page.locator('#volume').fill('7');await page.locator('#volume').dispatchEvent('input');
 await page.getByRole('button',{name:'文字練習',exact:true}).click();
 await page.locator('#hint').uncheck();await page.locator('#show-live').uncheck();
 await page.locator('#toggle-map').click();
 await page.reload();
 assert.equal(await page.locator('#speed').inputValue(),'23');
 assert.equal(await page.locator('#speed-value').textContent(),'23 WPM');
 assert.equal(await page.locator('#volume').inputValue(),'7');
 assert.equal(await page.locator('#hint').isChecked(),false);
 assert.equal(await page.locator('#show-live').isChecked(),false);
 assert.equal(await page.locator('#map-content').isVisible(),false);
 assert.equal(await page.locator('#sound').getAttribute('aria-pressed'),'false');
 assert.deepEqual(Object.keys(await page.evaluate(()=>JSON.parse(localStorage.getItem('morse-settings-v1')))).sort(),['auto','gap','group','hint','mapHidden','repeat','show-live','speed','volume'].sort());
 await page.evaluate(()=>localStorage.setItem('morse-settings-v1',JSON.stringify({speed:999,volume:'loud',hint:'false',group:'TMO'})));
 await page.reload();assert.equal(await page.locator('#speed').inputValue(),'18');assert.equal(await page.locator('#group').inputValue(),'all');
 await page.evaluate(()=>localStorage.setItem('morse-settings-v1','broken json'));
 await page.reload();assert.equal(await page.locator('#tree .node').count(),36);
 await page.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new Error('Storage blocked');}});});
 await page.reload();await page.locator('#toggle-map').click();assert.equal(await page.locator('#map-content').isVisible(),false);
 assert.match(await page.locator('#settings-note').textContent(),/保存できません/);
 assert.deepEqual(errors,[]);
 const touchPage=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
 await touchPage.goto('http://127.0.0.1:8772/tools/morse/');
 await touchPage.locator('#dit').scrollIntoViewIfNeeded();
 const touchPad=await touchPage.locator('#dit').boundingBox();
 const cdp=await touchPage.context().newCDPSession(touchPage);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchPad.x+36,y:touchPad.y+80}]});
 await touchPage.waitForTimeout(280);
 assert.ok((await touchPage.locator('#sequence').textContent()).length>=2,'Touch hold repeats');
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await touchPage.waitForTimeout(850);
 assert.equal(await touchPage.locator('#sequence').textContent(),'');
 assert.equal(await touchPage.locator('.paddle.firing').count(),0);
 await touchPage.close();
 console.log('PASS Edge: stationary hover beyond 5 marks, audible context, release, compact geometry, mouse A, automatic next question and mode cancellation, keyboard, mobile width, settings persistence and invalid/blocked storage, touch hold/release, no JS errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});