const {launch,instrument,root}=require('./helpers.cjs');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const artifacts=process.env.COMPOLAB_SCREENSHOTS||path.resolve(root,'../../outputs/compolab-validation/phase3');fs.mkdirSync(artifacts,{recursive:true});
const near=(a,b,t)=>assert.ok(Math.abs(a-b)<=t,`${a} != ${b} ±${t}`);
(async()=>{const env=await launch(),errors=[],external=[];try{
 const page=await env.browser.newPage({viewport:{width:1440,height:1000}});await instrument(page);
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(!r.url().startsWith(env.origin)&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))external.push(r.url());});
 await page.goto(env.origin+'/tools/compolab/');await page.waitForSelector('body[data-ready=true]',{timeout:90000});
 const result=await page.evaluate(async()=>{
  const THREE=await import('three'),{Stage3D}=await import('/tools/compolab/js/stage3d.js'),{modelParams}=await import('/tools/compolab/js/model3d.js'),{layer,scene}=await import('/tools/compolab/js/comp.js'),{BLENDS,blend}=await import('/tools/compolab/js/color.js');
  const r=__lab.renderer,stage=await __lab.getStage();const sc=new THREE.Scene(),cam=new THREE.OrthographicCamera(-1,1,1,-1,.1,10);cam.position.z=2;
  const mat=new THREE.MeshBasicMaterial({color:0x808080}),mesh=new THREE.Mesh(new THREE.PlaneGeometry(2,2),mat);sc.add(mesh);
  const read=(src,raw=true,scale=1)=>{const target=r.run('output',r.outputValues(scene(),{raw,scale,transparent:true}),{img:src,before:src},r.target(src.width,src.height,true));const data=new Uint8Array(src.width*src.height*4);r.gl.readPixels(0,0,src.width,src.height,r.gl.RGBA,r.gl.UNSIGNED_BYTE,data);r.release(target);return data;};
  const gray=Array.from(read(stage.draw(sc,cam,'color',3,3))).slice(16,20).map(x=>x/255);
  mat.color.setHex(0xffffff);mat.transparent=true;mat.opacity=.5;mat.needsUpdate=true;const alpha=Array.from(read(stage.draw(sc,cam,'color',3,3))).slice(16,20).map(x=>x/255);
  const blends={};for(const mode of Object.keys(BLENDS)){stage.draw(sc,cam,'color',3,3);const c=scene();c.width=c.height=1;const b=[.12,.45,.68],s=[.8,.3,.15];c.layers=[layer('solid','b',{params:{color:b}}),layer('solid','s',{params:{color:s},blend:mode})];const data=r.read(c,{raw:true,scale:.5});blends[mode]={actual:[...data.data.slice(0,3)],expected:blend(mode,b,s).map(x=>Math.round(Math.max(0,Math.min(1,x*.5))*255))};}
  await stage.sample();const c=scene();c.layers[1]=layer('render3d','3Dキャラ',{id:'character',role:'char',params:modelParams()});__lab.set(c);__lab.draw();
  const p=r.read(c,{role:'char',maxSize:256}),asset=stage.assets.get('sample:sotai_girl');let opaque=0,transparent=0;for(let i=3;i<p.data.length;i+=4){if(p.data[i]===255)opaque++;if(p.data[i]===0)transparent++;}
  const passes=stage.render(c.layers[1],256,144,{depth:true,normal:true,id:true});const depth=read(passes.depth,true,.1),normal=read(passes.normal),ids=read(passes.id);
  let zmin=Infinity,zmax=0,normals=0;for(let i=0;i<depth.length;i+=4)if(depth[i+3]){zmin=Math.min(zmin,depth[i]/255*10);zmax=Math.max(zmax,depth[i]/255*10);if(normal[i+2]>0)normals++;}
  c.layers[1].params.outline=false;const without=r.read(c,{role:'char',maxSize:256});const outlineChanges=p.data.reduce((n,v,i)=>n+(v!==without.data[i]),0);c.layers[1].params.outline=true;
  const {MToonMaterial}=await import('@pixiv/three-vrm');const sphere=new THREE.Mesh(new THREE.SphereGeometry(.4,32,16),new MToonMaterial({color:0x808080}));sphere.position.y=.85;stage.scene.add(sphere);const params=modelParams();params.lights.key.intensity=0;params.lights.fill.intensity=0;params.lights.rim.intensity=0;params.lights.hemi.intensity=0;stage.configure(params,65,65);const dark=read(stage.draw(stage.scene,stage.camera,'color',65,65));params.lights.key.intensity=2;stage.configure(params,65,65);const lit=read(stage.draw(stage.scene,stage.camera,'color',65,65));stage.scene.remove(sphere);const lightChanges=lit.reduce((n,v,i)=>n+(i%4!==3&&v>dark[i]),0);
  return {gray,alpha,blends,opaque,transparent,materials:asset.materials.map((m,i)=>({id:i+1,name:m.name,outline:m.isOutline,mtoon:m.isMToonMaterial})),outlineMeshes:asset.meshes.filter(m=>(Array.isArray(m.material)?m.material:[m.material]).some(v=>v.isOutline)).length,outlineChanges,linearDepth:{min:zmin,max:zmax},normalPixels:normals,lightChanges,passMax:{id:Math.max(...ids.filter((v,i)=>i%4===0))},glError:r.gl.getError()};
 });
 console.log('Shared context',JSON.stringify(result));
 await page.evaluate(()=>__lab.draw());await page.screenshot({path:path.join(artifacts,'shared-context.png'),fullPage:true});
 near(result.gray[0],.2159,.01);near(result.alpha[0],.5,.01);near(result.alpha[3],.5,.01);for(const v of Object.values(result.blends))v.actual.forEach((x,i)=>near(x,v.expected[i],1));assert.ok(result.opaque>100&&result.transparent>100);assert.ok(result.outlineMeshes>0);assert.equal(result.glError,0);
 assert.ok(result.outlineChanges>0&&result.normalPixels>0&&result.lightChanges>100);assert.ok(result.linearDepth.min>2&&result.linearDepth.max<5&&result.linearDepth.max>result.linearDepth.min);assert.equal(result.passMax.id,1);
 await page.evaluate(()=>__lab.draw());await page.screenshot({path:path.join(artifacts,'shared-context.png'),fullPage:true});
 // Four backgrounds: actual UI button and exact sky/ground agreement.
 result.lighting={};for(const bg of ['day','sunset','night','rain']){
  await page.selectOption('#sample',bg);await page.evaluate(()=>__lab.loadModel());await page.click('#lights-from-bg');
  result.lighting[bg]=await page.evaluate(async()=>{const {imageStats}=await import('/tools/compolab/js/color.js'),r=__lab.renderer,c=__lab.comp,p=r.read(c,{role:'bg',maxSize:256}),s=imageStats(p.data,p.width,p.height),l=c.layers.find(x=>x.type==='render3d').params.lights;__lab.draw();return {sky:l.hemi.sky,ground:l.hemi.ground,maxError:Math.max(...s.top.map((v,i)=>Math.abs(v-l.hemi.sky[i])),...s.bottom.map((v,i)=>Math.abs(v-l.hemi.ground[i])))};});assert.equal(result.lighting[bg].maxError,0);
  await page.screenshot({path:path.join(artifacts,'lighting-'+bg+'.png'),fullPage:true});await page.locator('#view').screenshot({path:path.join(artifacts,'lighting-'+bg+'-view.png')});
 }
 // Camera input forms a single undoable transaction, and does not zoom the 2D view.
 const cameraBefore=await page.evaluate(()=>JSON.stringify(__lab.comp.layers.find(l=>l.type==='render3d').params.camera));const hist=await page.evaluate(()=>__lab.history.past.length);
 const box=await page.locator('#view').boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.5,{steps:5});await page.mouse.up();
 assert.notEqual(await page.evaluate(()=>JSON.stringify(__lab.comp.layers.find(l=>l.type==='render3d').params.camera)),cameraBefore);assert.equal(await page.evaluate(()=>__lab.history.past.length),hist+1);assert.equal(await page.evaluate(()=>__lab.comp.view.zoom),1);await page.click('#undo');assert.equal(await page.evaluate(()=>JSON.stringify(__lab.comp.layers.find(l=>l.type==='render3d').params.camera)),cameraBefore);
 // 3D and 2D auto-match can be used together; one Undo restores the lights-only image.
 const before=await page.evaluate(()=>[...__lab.renderer.read(__lab.comp,{maxSize:256}).data]);await page.click('#auto-match');assert.ok(await page.evaluate(()=>__lab.comp.layers.some(l=>l.params.owner==='automatch')));await page.click('#undo');assert.deepEqual(await page.evaluate(()=>[...__lab.renderer.read(__lab.comp,{maxSize:256}).data]),before);
 // Local glTF through the real input. Hair ID changes, skin ID remains exact.
 const {fixture}=require('./model-fixture.cjs');await page.locator('#file-model').setInputFiles({name:'material-regions.gltf',mimeType:'model/gltf+json',buffer:fixture()});await page.waitForFunction(()=>__lab.comp.layers.some(l=>l.params.src==='user:material-regions.gltf'));
 result.id=await page.evaluate(async()=>{
  const {layer}=await import('/tools/compolab/js/comp.js'),{effect}=await import('/tools/compolab/js/effects.js');const c=__lab.comp,r=__lab.renderer,l=c.layers.find(l=>l.type==='render3d');l.params.passes.id=true;const a=r.read(c,{role:'char',maxSize:256});const id=r.layerPasses.get(l.id).id,target=r.run('output',r.outputValues(c,{raw:true}),{img:id,before:id},r.target(id.width,id.height,true));const raw=new Uint8Array(id.width*id.height*4);r.gl.readPixels(0,0,id.width,id.height,r.gl.RGBA,r.gl.UNSIGNED_BYTE,raw);r.release(target);
  c.layers.push(layer('adjust','髪の色相',{clipTo:l.id,mask:{source:'id:2',invert:false,feather:0},params:{kind:'colorgrade',...effect('colorgrade',{hue:80}).params}}));const b=r.read(c,{role:'char',maxSize:256});let skinMax=0,hairMax=0,skinPixels=0,hairPixels=0;for(let y=0;y<id.height;y++)for(let x=0;x<id.width;x++){const k=(y*id.width+x)*4,ik=((id.height-1-y)*id.width+x)*4,n=raw[ik];if(raw[ik+3]<255||a.data[k+3]<255)continue;const delta=Math.max(...[0,1,2].map(j=>Math.abs(a.data[k+j]-b.data[k+j])));if(n===1){skinMax=Math.max(skinMax,delta);skinPixels++;}if(n===2){hairMax=Math.max(hairMax,delta);hairPixels++;}}
  __lab.set(c);__lab.draw();return {skinMax,hairMax,skinPixels,hairPixels};
 });assert.equal(result.id.skinMax,0);assert.ok(result.id.hairMax>10&&result.id.skinPixels>100&&result.id.hairPixels>100);
 await page.screenshot({path:path.join(artifacts,'material-id.png'),fullPage:true});
 const stored=await page.evaluate(async()=>{const {validateScene}=await import('/tools/compolab/js/comp.js');return JSON.stringify(validateScene(__lab.comp));});const file={name:'material-regions.gltf',mimeType:'model/gltf+json',buffer:fixture()};await page.reload();await page.waitForSelector('body[data-ready=true]');assert.ok((await page.locator('#status').textContent()).includes('再読み込み'));await page.locator('#file-model').setInputFiles(file);await page.waitForFunction(()=>__lab.renderer.stage3d.assets.has('user:material-regions.gltf'));assert.equal(await page.evaluate(()=>JSON.stringify(__lab.comp)),stored);
 // Rejection happens before network access and cannot change the current scene.
 await page.locator('#file-model').setInputFiles({name:'external.gltf',mimeType:'model/gltf+json',buffer:fixture({external:true})});await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('外部URL'));assert.equal(await page.evaluate(()=>JSON.stringify(__lab.comp)),stored);
 // A sidecar .bin is resolved only from the selected local files.
 const sidecar=JSON.parse(fixture().toString()),bin=Buffer.from(sidecar.buffers[0].uri.split(',')[1],'base64');sidecar.buffers[0].uri='mesh.bin';
 await page.locator('#file-model').setInputFiles([{name:'sidecar.gltf',mimeType:'model/gltf+json',buffer:Buffer.from(JSON.stringify(sidecar))},{name:'mesh.bin',mimeType:'application/octet-stream',buffer:bin}]);await page.waitForFunction(()=>__lab.comp.layers.some(l=>l.params.src==='user:sidecar.gltf'));
 // GLB container follows the same import route (JSON chunk with an embedded buffer).
 const json=fixture(),padded=Buffer.alloc(Math.ceil(json.length/4)*4,32);json.copy(padded);const header=Buffer.alloc(20);header.writeUInt32LE(0x46546c67,0);header.writeUInt32LE(2,4);header.writeUInt32LE(20+padded.length,8);header.writeUInt32LE(padded.length,12);header.writeUInt32LE(0x4e4f534a,16);
 await page.locator('#file-model').setInputFiles({name:'regions.glb',mimeType:'model/gltf-binary',buffer:Buffer.concat([header,padded])});await page.waitForFunction(()=>__lab.comp.layers.some(l=>l.params.src==='user:regions.glb'));
 // Depth-driven fog/DOF and normal rim light all change the real VRM image.
 await page.evaluate(()=>__lab.loadPreset('char3d'));result.effects=await page.evaluate(async()=>{const {effect}=await import('/tools/compolab/js/effects.js'),r=__lab.renderer,c=__lab.comp,l=c.layers[1];l.effects=[];const base=r.read(c,{role:'char',maxSize:256}),result={};for(const [type,params] of [['fog',{density:.8,near:2,far:4}],['dof',{radius:.02,distance:2,range:1}],['rimlight',{intensity:.8}]]){l.effects=[effect(type,params)];const p=r.read(c,{role:'char',maxSize:256});result[type]=p.data.reduce((n,v,i)=>n+(v!==base.data[i]),0);}l.effects=[];return result;});for(const v of Object.values(result.effects))assert.ok(v>100);
 for(const kind of ['depth','normal','id']){await page.evaluate(kind=>{__lab.comp.layers[1].params.preview=kind;__lab.draw();},kind);await page.locator('#view').screenshot({path:path.join(artifacts,'pass-'+kind+'.png')});}
 await page.evaluate(()=>{__lab.comp.layers[1].params.preview='color';__lab.draw();});
 // Orthographic wheel zoom is saved and undoable, with 2D pan staying independent.
 await page.evaluate(()=>{const l=__lab.comp.layers[1];l.params.camera.ortho=true;__lab.set(__lab.comp);__lab.draw();});
 const vp=await page.locator('#view').boundingBox();await page.mouse.move(vp.x+vp.width/2,vp.y+vp.height/2);await page.mouse.wheel(0,-120);await page.waitForFunction(()=>__lab.comp.layers[1].params.camera.zoom>1);
 const ortho=await page.evaluate(()=>JSON.stringify(__lab.comp.layers[1].params.camera));await page.reload();await page.waitForSelector('body[data-ready=true]');assert.equal(await page.evaluate(()=>JSON.stringify(__lab.comp.layers[1].params.camera)),ortho);
 await page.locator('#viewport').focus();await page.keyboard.down('Space');await page.mouse.move(vp.x+vp.width/2,vp.y+vp.height/2);await page.mouse.down();await page.mouse.move(vp.x+vp.width/2+20,vp.y+vp.height/2+10);await page.mouse.up();await page.keyboard.up('Space');assert.equal(await page.evaluate(()=>JSON.stringify(__lab.comp.layers[1].params.camera)),ortho);await page.click('#fit');
 // Transparent PNG export retains every displayed character pixel and alpha.
 const ref=await page.evaluate(async()=>{const p=__lab.renderer.read(__lab.comp,{role:'char',maxSize:4096});return {width:p.width,height:p.height,hash:[...new Uint8Array(await crypto.subtle.digest('SHA-256',p.data))].map(x=>x.toString(16).padStart(2,'0')).join('')};});
 const dlPromise=page.waitForEvent('download');await page.evaluate(()=>__lab.exportFile('char'));const dl=await dlPromise,exportPath=path.join(artifacts,'character.png');await dl.saveAs(exportPath);const {PNG}=require('pngjs'),decoded=PNG.sync.read(fs.readFileSync(exportPath));assert.equal(require('node:crypto').createHash('sha256').update(decoded.data).digest('hex'),ref.hash);assert.equal(decoded.width,1920);assert.equal(decoded.height,1080);result.export={width:1920,height:1080,maxPixelError:0};
 for(const width of [375,768,1280]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(artifacts,'layout-'+width+'.png'),fullPage:true});}
 result.consoleErrors=errors.length;result.externalRequests=external.length;assert.deepEqual(errors,[]);assert.deepEqual(external,[]);fs.writeFileSync(path.join(artifacts,'results.json'),JSON.stringify(result,null,2)+'\n');console.log('Phase 3 acceptance PASS',JSON.stringify({id:result.id,effects:result.effects,lighting:result.lighting}));
 }finally{await env.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
